-- App 隐私合规检测系统知识库与扫描结果库
-- 目标数据库：PostgreSQL 13+
-- 设计原则：知识规则与扫描运行数据分离；所有规则保留来源、置信度、版本和原始数据。

BEGIN;

CREATE SCHEMA IF NOT EXISTS privacy_kb;
CREATE SCHEMA IF NOT EXISTS privacy_scan;

-- ============================================================
-- 通用更新时间触发器
-- ============================================================
CREATE OR REPLACE FUNCTION privacy_kb.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ============================================================
-- 一、知识库导入批次
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.import_batch (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file         text NOT NULL,
    source_sha256       varchar(64),
    import_mode         varchar(20) NOT NULL DEFAULT 'UPSERT',
    status              varchar(20) NOT NULL DEFAULT 'RUNNING',
    started_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at         timestamptz,
    statistics          jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_message       text,
    created_by          varchar(100),
    CONSTRAINT ck_import_batch_mode CHECK (import_mode IN ('UPSERT', 'REPLACE', 'DRY_RUN')),
    CONSTRAINT ck_import_batch_status CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED', 'ROLLED_BACK'))
);
CREATE INDEX IF NOT EXISTS idx_import_batch_sha256 ON privacy_kb.import_batch(source_sha256);
CREATE INDEX IF NOT EXISTS idx_import_batch_started ON privacy_kb.import_batch(started_at DESC);

-- ============================================================
-- 二、厂商、数据来源
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.vendor (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_key          varchar(160) NOT NULL UNIQUE,
    name                varchar(300) NOT NULL,
    normalized_name     varchar(300) NOT NULL,
    official_website    text,
    country_or_region   varchar(100),
    verification_status varchar(30) NOT NULL DEFAULT 'UNVERIFIED',
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_vendor_verify CHECK (verification_status IN ('VERIFIED', 'PARTIAL', 'UNVERIFIED', 'PENDING_VENDOR_CONFIRM'))
);
CREATE INDEX IF NOT EXISTS idx_vendor_normalized_name ON privacy_kb.vendor(normalized_name);

DROP TRIGGER IF EXISTS trg_vendor_updated_at ON privacy_kb.vendor;
CREATE TRIGGER trg_vendor_updated_at
BEFORE UPDATE ON privacy_kb.vendor
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_kb.source (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key          varchar(180) NOT NULL UNIQUE,
    name                varchar(500) NOT NULL,
    source_type         varchar(80),
    coverage            text,
    url                 text,
    kb_usage            text,
    trust_level         varchar(20),
    maintenance_advice  text,
    source_version      varchar(100),
    published_at        timestamptz,
    fetched_at          timestamptz,
    snapshot_sha256     varchar(64),
    is_active           boolean NOT NULL DEFAULT true,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_source_type ON privacy_kb.source(source_type);
CREATE INDEX IF NOT EXISTS idx_source_url ON privacy_kb.source(url);

DROP TRIGGER IF EXISTS trg_source_updated_at ON privacy_kb.source;
CREATE TRIGGER trg_source_updated_at
BEFORE UPDATE ON privacy_kb.source
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

-- ============================================================
-- 三、统一软件组件知识库
-- SDK、开源库、框架、系统组件、厂商业务组件、应用模块均进入该表。
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.component (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_key           varchar(180) NOT NULL UNIQUE,
    name                    varchar(500) NOT NULL,
    normalized_name         varchar(500) NOT NULL,
    english_name            varchar(500),
    vendor_id               bigint REFERENCES privacy_kb.vendor(id),
    component_kind          varchar(50) NOT NULL DEFAULT 'UNKNOWN',
    category_l1             varchar(150),
    category_l2             varchar(150),
    primary_purpose         text,
    description             text,
    attributes              text,
    license_name            varchar(200),
    sensitivity_level       varchar(20),
    confidence_level        varchar(20),
    verification_status     varchar(40) NOT NULL DEFAULT 'PENDING',
    source_type             varchar(200),
    recommended_match_rule  text,
    obfuscation_handling    text,
    false_positive_note     text,
    compliance_note         text,
    is_active               boolean NOT NULL DEFAULT true,
    record_version          integer NOT NULL DEFAULT 1,
    first_seen_at           timestamptz,
    last_verified_at        timestamptz,
    raw_data                jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_component_kind CHECK (component_kind IN (
        'SDK', 'OPEN_SOURCE_LIBRARY', 'FRAMEWORK', 'SYSTEM_COMPONENT',
        'VENDOR_COMPONENT', 'APP_MODULE', 'TOOLING', 'UNKNOWN'
    )),
    CONSTRAINT ck_component_sensitivity CHECK (
        sensitivity_level IS NULL OR sensitivity_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN')
    ),
    CONSTRAINT ck_component_confidence CHECK (
        confidence_level IS NULL OR confidence_level IN ('LOW', 'MEDIUM', 'HIGH', 'UNKNOWN')
    )
);
CREATE INDEX IF NOT EXISTS idx_component_name ON privacy_kb.component(normalized_name);
CREATE INDEX IF NOT EXISTS idx_component_vendor ON privacy_kb.component(vendor_id);
CREATE INDEX IF NOT EXISTS idx_component_kind ON privacy_kb.component(component_kind);
CREATE INDEX IF NOT EXISTS idx_component_category ON privacy_kb.component(category_l1, category_l2);
CREATE INDEX IF NOT EXISTS idx_component_active ON privacy_kb.component(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_component_raw_data_gin ON privacy_kb.component USING gin(raw_data);

DROP TRIGGER IF EXISTS trg_component_updated_at ON privacy_kb.component;
CREATE TRIGGER trg_component_updated_at
BEFORE UPDATE ON privacy_kb.component
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_kb.component_alias (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id        bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    alias_name          varchar(500) NOT NULL,
    normalized_alias    varchar(500) NOT NULL,
    alias_type          varchar(30) NOT NULL DEFAULT 'OTHER',
    language_code       varchar(20),
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(component_id, normalized_alias),
    CONSTRAINT ck_component_alias_type CHECK (alias_type IN ('ENGLISH_NAME', 'PRODUCT_NAME', 'OLD_NAME', 'PACKAGE_NAME', 'OTHER'))
);
CREATE INDEX IF NOT EXISTS idx_component_alias_lookup ON privacy_kb.component_alias(normalized_alias);

-- ============================================================
-- 四、组件指纹
-- 推荐把检测引擎输出的原始特征统一映射到本表。
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.component_fingerprint (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id            bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    fingerprint_type        varchar(50) NOT NULL,
    value                   text NOT NULL,
    normalized_value        text NOT NULL,
    match_mode              varchar(20) NOT NULL DEFAULT 'EXACT',
    manifest_component_type varchar(20),
    evidence_role           varchar(20) NOT NULL DEFAULT 'SUPPORTING',
    weight                  smallint NOT NULL DEFAULT 10,
    confidence_level        varchar(20),
    is_negative             boolean NOT NULL DEFAULT false,
    is_stable               boolean,
    version_from            varchar(100),
    version_to              varchar(100),
    source_id               bigint REFERENCES privacy_kb.source(id),
    source_batch_id         bigint REFERENCES privacy_kb.import_batch(id),
    raw_data                jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(component_id, fingerprint_type, normalized_value, match_mode),
    CONSTRAINT ck_fingerprint_type CHECK (fingerprint_type IN (
        'PACKAGE_PREFIX', 'CLASS', 'MANIFEST_ACTIVITY', 'MANIFEST_SERVICE',
        'MANIFEST_RECEIVER', 'MANIFEST_PROVIDER', 'MAVEN_COORDINATE',
        'NATIVE_SO', 'RESOURCE', 'PERMISSION', 'API_SIGNATURE', 'FIELD',
        'META_DATA', 'INTENT_ACTION', 'DOMAIN', 'URL', 'STRING',
        'CERTIFICATE', 'FILE_HASH', 'METHOD_HASH', 'OTHER'
    )),
    CONSTRAINT ck_fingerprint_match_mode CHECK (match_mode IN ('EXACT', 'PREFIX', 'SUFFIX', 'CONTAINS', 'REGEX', 'HASH')),
    CONSTRAINT ck_fingerprint_role CHECK (evidence_role IN ('PRIMARY', 'SUPPORTING', 'NEGATIVE')),
    CONSTRAINT ck_fingerprint_weight CHECK (weight BETWEEN -100 AND 100)
);
CREATE INDEX IF NOT EXISTS idx_fingerprint_exact ON privacy_kb.component_fingerprint(fingerprint_type, normalized_value);
CREATE INDEX IF NOT EXISTS idx_fingerprint_component ON privacy_kb.component_fingerprint(component_id);
CREATE INDEX IF NOT EXISTS idx_fingerprint_type_mode ON privacy_kb.component_fingerprint(fingerprint_type, match_mode);
CREATE INDEX IF NOT EXISTS idx_fingerprint_prefix_text ON privacy_kb.component_fingerprint(normalized_value text_pattern_ops)
    WHERE match_mode = 'PREFIX';
CREATE INDEX IF NOT EXISTS idx_fingerprint_raw_gin ON privacy_kb.component_fingerprint USING gin(raw_data);

DROP TRIGGER IF EXISTS trg_fingerprint_updated_at ON privacy_kb.component_fingerprint;
CREATE TRIGGER trg_fingerprint_updated_at
BEFORE UPDATE ON privacy_kb.component_fingerprint
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_kb.component_relation (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_component_id bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    child_component_id  bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    relation_type       varchar(30) NOT NULL,
    description         text,
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(parent_component_id, child_component_id, relation_type),
    CONSTRAINT ck_component_relation_type CHECK (relation_type IN (
        'DEPENDS_ON', 'BUNDLES', 'PUSH_CHANNEL', 'REPLACES', 'VARIANT_OF',
        'FORK_OF', 'WRAPS', 'PART_OF', 'OTHER'
    )),
    CONSTRAINT ck_component_relation_self CHECK (parent_component_id <> child_component_id)
);

-- ============================================================
-- 五、权限知识库及组件权限关系
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.permission (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name     varchar(500) NOT NULL UNIQUE,
    normalized_name     varchar(500) NOT NULL,
    category            varchar(150),
    capability          text,
    permission_type     varchar(100),
    risk_level          varchar(20),
    grant_mode          text,
    compliance_focus    text,
    official_reference  text,
    is_active           boolean NOT NULL DEFAULT true,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_permission_category ON privacy_kb.permission(category);
CREATE INDEX IF NOT EXISTS idx_permission_risk ON privacy_kb.permission(risk_level);

DROP TRIGGER IF EXISTS trg_permission_updated_at ON privacy_kb.permission;
CREATE TRIGGER trg_permission_updated_at
BEFORE UPDATE ON privacy_kb.permission
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_kb.component_permission (
    component_id        bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    permission_id       bigint NOT NULL REFERENCES privacy_kb.permission(id) ON DELETE CASCADE,
    relation_type       varchar(20) NOT NULL DEFAULT 'TYPICAL',
    evidence_weight     smallint NOT NULL DEFAULT 5,
    notes               text,
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(component_id, permission_id, relation_type),
    CONSTRAINT ck_component_permission_type CHECK (relation_type IN ('REQUIRED', 'OPTIONAL', 'TYPICAL', 'OBSERVED', 'INHERITED'))
);
CREATE INDEX IF NOT EXISTS idx_component_permission_permission ON privacy_kb.component_permission(permission_id);

-- ============================================================
-- 六、移动端个人信息/系统能力知识库
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.data_item (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_key            varchar(180) NOT NULL UNIQUE,
    category_l1         varchar(150) NOT NULL,
    category_l2         varchar(200),
    item_name           varchar(300) NOT NULL,
    typical_fields      text,
    possible_data       text,
    personal_info_type  text,
    sensitivity_level   varchar(20),
    compliance_focus    text,
    is_active           boolean NOT NULL DEFAULT true,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_item_sensitivity CHECK (
        sensitivity_level IS NULL OR sensitivity_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN')
    )
);
CREATE INDEX IF NOT EXISTS idx_data_item_category ON privacy_kb.data_item(category_l1, category_l2);

DROP TRIGGER IF EXISTS trg_data_item_updated_at ON privacy_kb.data_item;
CREATE TRIGGER trg_data_item_updated_at
BEFORE UPDATE ON privacy_kb.data_item
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_kb.data_detection_pattern (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_item_id        bigint NOT NULL REFERENCES privacy_kb.data_item(id) ON DELETE CASCADE,
    pattern_type        varchar(30) NOT NULL,
    value               text NOT NULL,
    normalized_value    text NOT NULL,
    match_mode          varchar(20) NOT NULL DEFAULT 'CONTAINS',
    detection_stage     varchar(20) NOT NULL DEFAULT 'BOTH',
    weight              smallint NOT NULL DEFAULT 10,
    notes               text,
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(data_item_id, pattern_type, normalized_value, detection_stage),
    CONSTRAINT ck_data_pattern_type CHECK (pattern_type IN ('API', 'CLASS', 'FIELD', 'PERMISSION', 'HOOK', 'KEYWORD', 'URI', 'OTHER')),
    CONSTRAINT ck_data_pattern_stage CHECK (detection_stage IN ('STATIC', 'DYNAMIC', 'BOTH')),
    CONSTRAINT ck_data_pattern_match CHECK (match_mode IN ('EXACT', 'PREFIX', 'SUFFIX', 'CONTAINS', 'REGEX'))
);
CREATE INDEX IF NOT EXISTS idx_data_pattern_lookup ON privacy_kb.data_detection_pattern(pattern_type, normalized_value);

CREATE TABLE IF NOT EXISTS privacy_kb.component_data_claim (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id            bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    claim_key               varchar(180) NOT NULL,
    data_item_id            bigint REFERENCES privacy_kb.data_item(id),
    data_description        text,
    personal_info_category  text,
    sensitivity_level       varchar(20),
    collection_mode         varchar(30) NOT NULL DEFAULT 'POSSIBLE',
    purpose                 text,
    compliance_note         text,
    source_batch_id         bigint REFERENCES privacy_kb.import_batch(id),
    raw_data                jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(component_id, claim_key),
    CONSTRAINT ck_data_claim_mode CHECK (collection_mode IN ('POSSIBLE', 'REQUIRED', 'OPTIONAL', 'DEFAULT', 'OBSERVED', 'DEVELOPER_PROVIDED'))
);
CREATE INDEX IF NOT EXISTS idx_component_data_claim_component ON privacy_kb.component_data_claim(component_id);
CREATE INDEX IF NOT EXISTS idx_component_data_claim_item ON privacy_kb.component_data_claim(data_item_id);

DROP TRIGGER IF EXISTS trg_component_data_claim_updated_at ON privacy_kb.component_data_claim;
CREATE TRIGGER trg_component_data_claim_updated_at
BEFORE UPDATE ON privacy_kb.component_data_claim
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

-- ============================================================
-- 七、来源关系、识别规则、维护策略
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_kb.component_source (
    component_id        bigint NOT NULL REFERENCES privacy_kb.component(id) ON DELETE CASCADE,
    source_id           bigint NOT NULL REFERENCES privacy_kb.source(id) ON DELETE CASCADE,
    source_role         varchar(30) NOT NULL DEFAULT 'REFERENCE',
    evidence_note       text,
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(component_id, source_id, source_role),
    CONSTRAINT ck_component_source_role CHECK (source_role IN ('OFFICIAL', 'REPOSITORY', 'PRIVACY_POLICY', 'SAMPLE_EVIDENCE', 'REFERENCE'))
);

CREATE TABLE IF NOT EXISTS privacy_kb.recognition_rule (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_key            varchar(180) NOT NULL UNIQUE,
    rule_level          varchar(100),
    evidence_type       varchar(100) NOT NULL,
    suggested_score     integer NOT NULL DEFAULT 0,
    detection_content   text,
    applicable_object   text,
    decision_advice     text,
    obfuscation_support text,
    false_positive_ctrl text,
    engine_min_version  varchar(50),
    rule_version        integer NOT NULL DEFAULT 1,
    is_active           boolean NOT NULL DEFAULT true,
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recognition_rule_score CHECK (suggested_score BETWEEN -100 AND 100)
);
CREATE INDEX IF NOT EXISTS idx_recognition_rule_evidence ON privacy_kb.recognition_rule(evidence_type);

DROP TRIGGER IF EXISTS trg_recognition_rule_updated_at ON privacy_kb.recognition_rule;
CREATE TRIGGER trg_recognition_rule_updated_at
BEFORE UPDATE ON privacy_kb.recognition_rule
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_kb.maintenance_policy (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_key          varchar(180) NOT NULL UNIQUE,
    maintenance_object  varchar(200) NOT NULL,
    unique_key_advice   text,
    required_version_fields text,
    update_trigger      text,
    quality_control     text,
    is_active           boolean NOT NULL DEFAULT true,
    source_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_maintenance_policy_updated_at ON privacy_kb.maintenance_policy;
CREATE TRIGGER trg_maintenance_policy_updated_at
BEFORE UPDATE ON privacy_kb.maintenance_policy
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

-- ============================================================
-- 八、扫描运行数据
-- ============================================================
CREATE TABLE IF NOT EXISTS privacy_scan.app (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_name        varchar(500) NOT NULL UNIQUE,
    app_name            varchar(500),
    platform            varchar(20) NOT NULL DEFAULT 'ANDROID',
    owner_org           varchar(300),
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_scan_app_updated_at ON privacy_scan.app;
CREATE TRIGGER trg_scan_app_updated_at
BEFORE UPDATE ON privacy_scan.app
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_scan.app_build (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_key           varchar(180) NOT NULL UNIQUE,
    app_id              bigint NOT NULL REFERENCES privacy_scan.app(id) ON DELETE CASCADE,
    version_name        varchar(100),
    version_code        varchar(100),
    min_sdk             integer,
    target_sdk          integer,
    max_sdk             integer,
    file_size           bigint,
    sha256              varchar(64),
    source_file         text,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(app_id, version_code, sha256)
);
CREATE INDEX IF NOT EXISTS idx_app_build_sha256 ON privacy_scan.app_build(sha256);
CREATE INDEX IF NOT EXISTS idx_app_build_app ON privacy_scan.app_build(app_id, created_at DESC);

CREATE TABLE IF NOT EXISTS privacy_scan.scan_job (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_build_id        bigint NOT NULL REFERENCES privacy_scan.app_build(id) ON DELETE CASCADE,
    scan_type           varchar(30) NOT NULL DEFAULT 'STATIC',
    engine_version      varchar(100),
    rule_version        varchar(100),
    status              varchar(20) NOT NULL DEFAULT 'RUNNING',
    started_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at         timestamptz,
    summary             jsonb NOT NULL DEFAULT '{}'::jsonb,
    import_batch_id     bigint REFERENCES privacy_kb.import_batch(id),
    error_message       text,
    CONSTRAINT ck_scan_type CHECK (scan_type IN ('STATIC', 'DYNAMIC', 'HYBRID', 'EXCEL_IMPORT')),
    CONSTRAINT ck_scan_status CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL'))
);
CREATE INDEX IF NOT EXISTS idx_scan_job_build ON privacy_scan.scan_job(app_build_id, started_at DESC);

CREATE TABLE IF NOT EXISTS privacy_scan.manifest_component (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_job_id         bigint NOT NULL REFERENCES privacy_scan.scan_job(id) ON DELETE CASCADE,
    component_type      varchar(20) NOT NULL,
    class_name          text NOT NULL,
    package_name        text,
    exported            boolean,
    enabled             boolean,
    declared_permission text,
    matched_component_id bigint REFERENCES privacy_kb.component(id),
    match_confidence    varchar(20),
    risk_level          varchar(20),
    purpose             text,
    data_description    text,
    personal_info_category text,
    review_focus        text,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(scan_job_id, component_type, class_name)
);
CREATE INDEX IF NOT EXISTS idx_manifest_component_class ON privacy_scan.manifest_component(class_name);
CREATE INDEX IF NOT EXISTS idx_manifest_component_matched ON privacy_scan.manifest_component(matched_component_id);

CREATE TABLE IF NOT EXISTS privacy_scan.declared_permission (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_job_id         bigint NOT NULL REFERENCES privacy_scan.scan_job(id) ON DELETE CASCADE,
    permission_name     varchar(500) NOT NULL,
    permission_id       bigint REFERENCES privacy_kb.permission(id),
    is_dangerous        boolean,
    risk_level          varchar(20),
    compliance_focus    text,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(scan_job_id, permission_name)
);
CREATE INDEX IF NOT EXISTS idx_declared_permission_permission ON privacy_scan.declared_permission(permission_id);

CREATE TABLE IF NOT EXISTS privacy_scan.package_cluster (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_job_id         bigint NOT NULL REFERENCES privacy_scan.scan_job(id) ON DELETE CASCADE,
    package_prefix      text NOT NULL,
    identified_name     text,
    component_kind      varchar(50),
    vendor_name         text,
    category            text,
    primary_purpose     text,
    component_count     integer,
    component_type_stat jsonb NOT NULL DEFAULT '{}'::jsonb,
    matched_component_id bigint REFERENCES privacy_kb.component(id),
    risk_level          varchar(20),
    confidence_level    varchar(20),
    evidence_basis      text,
    review_focus        text,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(scan_job_id, package_prefix)
);
CREATE INDEX IF NOT EXISTS idx_package_cluster_prefix ON privacy_scan.package_cluster(package_prefix text_pattern_ops);
CREATE INDEX IF NOT EXISTS idx_package_cluster_component ON privacy_scan.package_cluster(matched_component_id);

CREATE TABLE IF NOT EXISTS privacy_scan.component_hit (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_job_id         bigint NOT NULL REFERENCES privacy_scan.scan_job(id) ON DELETE CASCADE,
    component_id        bigint NOT NULL REFERENCES privacy_kb.component(id),
    total_score         integer NOT NULL DEFAULT 0,
    confidence_level    varchar(20),
    detected_version    varchar(100),
    hit_status          varchar(20) NOT NULL DEFAULT 'CANDIDATE',
    primary_package     text,
    evidence_count      integer NOT NULL DEFAULT 0,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(scan_job_id, component_id),
    CONSTRAINT ck_component_hit_status CHECK (hit_status IN ('CONFIRMED', 'PROBABLE', 'CANDIDATE', 'REJECTED', 'WHITELISTED'))
);
CREATE INDEX IF NOT EXISTS idx_component_hit_scan ON privacy_scan.component_hit(scan_job_id, total_score DESC);

DROP TRIGGER IF EXISTS trg_component_hit_updated_at ON privacy_scan.component_hit;
CREATE TRIGGER trg_component_hit_updated_at
BEFORE UPDATE ON privacy_scan.component_hit
FOR EACH ROW EXECUTE FUNCTION privacy_kb.set_updated_at();

CREATE TABLE IF NOT EXISTS privacy_scan.hit_evidence (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_hit_id    bigint NOT NULL REFERENCES privacy_scan.component_hit(id) ON DELETE CASCADE,
    fingerprint_id      bigint REFERENCES privacy_kb.component_fingerprint(id),
    evidence_type       varchar(50) NOT NULL,
    evidence_value      text NOT NULL,
    evidence_location   text,
    score               integer NOT NULL DEFAULT 0,
    is_primary          boolean NOT NULL DEFAULT false,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(component_hit_id, evidence_type, evidence_value, evidence_location)
);
CREATE INDEX IF NOT EXISTS idx_hit_evidence_hit ON privacy_scan.hit_evidence(component_hit_id);

CREATE TABLE IF NOT EXISTS privacy_scan.data_finding (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_job_id         bigint NOT NULL REFERENCES privacy_scan.scan_job(id) ON DELETE CASCADE,
    data_item_id        bigint REFERENCES privacy_kb.data_item(id),
    component_hit_id    bigint REFERENCES privacy_scan.component_hit(id),
    finding_type        varchar(30) NOT NULL,
    risk_level          varchar(20),
    confidence_level    varchar(20),
    purpose             text,
    evidence            text,
    policy_disclosure_status varchar(30),
    remediation         text,
    raw_data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_data_finding_type CHECK (finding_type IN (
        'CAPABILITY', 'STATIC_API', 'DYNAMIC_ACCESS', 'SDK_CLAIM',
        'PERMISSION', 'POLICY_MISMATCH', 'EXCESSIVE_COLLECTION', 'OTHER'
    ))
);
CREATE INDEX IF NOT EXISTS idx_data_finding_scan ON privacy_scan.data_finding(scan_job_id, risk_level);
CREATE INDEX IF NOT EXISTS idx_data_finding_item ON privacy_scan.data_finding(data_item_id);

-- ============================================================
-- 九、常用视图
-- ============================================================
CREATE OR REPLACE VIEW privacy_kb.v_component_fingerprint AS
SELECT
    c.id AS component_id,
    c.name AS component_name,
    c.component_kind,
    c.category_l1,
    c.category_l2,
    v.name AS vendor_name,
    f.id AS fingerprint_id,
    f.fingerprint_type,
    f.value,
    f.normalized_value,
    f.match_mode,
    f.weight,
    f.confidence_level,
    f.evidence_role,
    f.is_negative,
    c.verification_status,
    c.is_active
FROM privacy_kb.component c
LEFT JOIN privacy_kb.vendor v ON v.id = c.vendor_id
JOIN privacy_kb.component_fingerprint f ON f.component_id = c.id;

CREATE OR REPLACE VIEW privacy_kb.v_component_privacy_profile AS
SELECT
    c.id AS component_id,
    c.name AS component_name,
    v.name AS vendor_name,
    c.component_kind,
    c.category_l1,
    c.sensitivity_level,
    COALESCE(
        jsonb_agg(DISTINCT jsonb_build_object(
            'description', d.data_description,
            'category', d.personal_info_category,
            'sensitivity', d.sensitivity_level,
            'mode', d.collection_mode,
            'purpose', d.purpose
        )) FILTER (WHERE d.id IS NOT NULL),
        '[]'::jsonb
    ) AS data_claims,
    COALESCE(
        jsonb_agg(DISTINCT jsonb_build_object(
            'permission', p.permission_name,
            'risk', p.risk_level,
            'relation', cp.relation_type
        )) FILTER (WHERE p.id IS NOT NULL),
        '[]'::jsonb
    ) AS permissions
FROM privacy_kb.component c
LEFT JOIN privacy_kb.vendor v ON v.id = c.vendor_id
LEFT JOIN privacy_kb.component_data_claim d ON d.component_id = c.id
LEFT JOIN privacy_kb.component_permission cp ON cp.component_id = c.id
LEFT JOIN privacy_kb.permission p ON p.id = cp.permission_id
GROUP BY c.id, c.name, v.name, c.component_kind, c.category_l1, c.sensitivity_level;

CREATE OR REPLACE VIEW privacy_scan.v_scan_component_result AS
SELECT
    sj.id AS scan_job_id,
    a.package_name,
    a.app_name,
    b.version_name,
    b.version_code,
    c.name AS component_name,
    v.name AS vendor_name,
    c.component_kind,
    h.total_score,
    h.confidence_level,
    h.hit_status,
    h.primary_package,
    h.evidence_count,
    c.sensitivity_level,
    c.compliance_note
FROM privacy_scan.component_hit h
JOIN privacy_scan.scan_job sj ON sj.id = h.scan_job_id
JOIN privacy_scan.app_build b ON b.id = sj.app_build_id
JOIN privacy_scan.app a ON a.id = b.app_id
JOIN privacy_kb.component c ON c.id = h.component_id
LEFT JOIN privacy_kb.vendor v ON v.id = c.vendor_id;

COMMIT;

-- 可选优化：有扩展安装权限时启用模糊搜索。
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- CREATE INDEX idx_component_name_trgm ON privacy_kb.component USING gin(normalized_name gin_trgm_ops);
-- CREATE INDEX idx_fingerprint_value_trgm ON privacy_kb.component_fingerprint USING gin(normalized_value gin_trgm_ops);
